using System;
using System.Runtime.InteropServices;

namespace OpenGL
{
    // Automatically generated from GlCore.cs using BuildGl
    partial class Gl
    {
        internal static partial class Delegates
        {
            internal delegate void ActiveTexture(OpenGL.TextureUnit texture);
            internal static ActiveTexture glActiveTexture;
            internal delegate void AttachShader(UInt32 program, UInt32 shader);
            internal static AttachShader glAttachShader;
            internal delegate void BeginConditionalRender(UInt32 id, OpenGL.ConditionalRenderType mode);
            internal static BeginConditionalRender glBeginConditionalRender;
            internal delegate void BeginQuery(OpenGL.QueryTarget target, UInt32 id);
            internal static BeginQuery glBeginQuery;
            internal delegate void BeginTransformFeedback(OpenGL.BeginFeedbackMode primitiveMode);
            internal static BeginTransformFeedback glBeginTransformFeedback;
            internal delegate void BindAttribLocation(UInt32 program, UInt32 index, String name);
            internal static BindAttribLocation glBindAttribLocation;
            internal delegate void BindBuffer(OpenGL.BufferTarget target, UInt32 buffer);
            internal static BindBuffer glBindBuffer;
            internal delegate void BindBufferBase(OpenGL.BufferTarget target, UInt32 index, UInt32 buffer);
            internal static BindBufferBase glBindBufferBase;
            internal delegate void BindBufferRange(BufferTarget target, UInt32 index, UInt32 buffer, IntPtr offset, IntPtr size);
            internal static BindBufferRange glBindBufferRange;
            internal delegate void BindFragDataLocation(UInt32 program, UInt32 color, String name);
            internal static BindFragDataLocation glBindFragDataLocation;
            internal delegate void BindFramebuffer(OpenGL.FramebufferTarget target, UInt32 framebuffer);
            internal static BindFramebuffer glBindFramebuffer;
            internal delegate void BindRenderbuffer(OpenGL.RenderbufferTarget target, UInt32 renderbuffer);
            internal static BindRenderbuffer glBindRenderbuffer;
            internal delegate void BindTexture(OpenGL.TextureTarget target, UInt32 texture);
            internal static BindTexture glBindTexture;
            internal delegate void BindTransformFeedbackNV(OpenGL.NvTransformFeedback2 target, UInt32 id);
            internal static BindTransformFeedbackNV glBindTransformFeedbackNV;
            internal delegate void BindVertexArray(UInt32 array);
            internal static BindVertexArray glBindVertexArray;
            internal delegate void BlendColor(Single red, Single green, Single blue, Single alpha);
            internal static BlendColor glBlendColor;
            internal delegate void BlendEquation(OpenGL.BlendEquationMode mode);
            internal static BlendEquation glBlendEquation;
            internal delegate void BlendEquationSeparate(OpenGL.BlendEquationMode modeRGB, OpenGL.BlendEquationMode modeAlpha);
            internal static BlendEquationSeparate glBlendEquationSeparate;
            internal delegate void BlendFunc(OpenGL.BlendingFactorSrc sfactor, OpenGL.BlendingFactorDest dfactor);
            internal static BlendFunc glBlendFunc;
            internal delegate void BlendFuncSeparate(OpenGL.BlendingFactorSrc sfactorRGB, OpenGL.BlendingFactorDest dfactorRGB, OpenGL.BlendingFactorSrc sfactorAlpha, OpenGL.BlendingFactorDest dfactorAlpha);
            internal static BlendFuncSeparate glBlendFuncSeparate;
            internal delegate void BlitFramebuffer(Int32 srcX0, Int32 srcY0, Int32 srcX1, Int32 srcY1, Int32 dstX0, Int32 dstY0, Int32 dstX1, Int32 dstY1, OpenGL.ClearBufferMask mask, OpenGL.BlitFramebufferFilter filter);
            internal static BlitFramebuffer glBlitFramebuffer;
            internal delegate void BufferData(OpenGL.BufferTarget target, IntPtr size, IntPtr data, OpenGL.BufferUsageHint usage);
            internal static BufferData glBufferData;
            internal delegate void BufferSubData(OpenGL.BufferTarget target, IntPtr offset, IntPtr size, IntPtr data);
            internal static BufferSubData glBufferSubData;
            internal delegate OpenGL.FramebufferErrorCode CheckFramebufferStatus(OpenGL.FramebufferTarget target);
            internal static CheckFramebufferStatus glCheckFramebufferStatus;
            internal delegate void ClampColor(OpenGL.ClampColorTarget target, OpenGL.ClampColorMode clamp);
            internal static ClampColor glClampColor;
            internal delegate void Clear(OpenGL.ClearBufferMask mask);
            internal static Clear glClear;
            internal delegate void ClearBufferfi(OpenGL.ClearBuffer buffer, Int32 drawbuffer, Single depth, Int32 stencil);
            internal static ClearBufferfi glClearBufferfi;
            internal delegate void ClearDepth(Double depth);
            internal static ClearDepth glClearDepth;
            internal delegate void ClearStencil(Int32 s);
            internal static ClearStencil glClearStencil;
            internal delegate OpenGL.ArbSync ClientWaitSync(IntPtr sync, UInt32 flags, UInt64 timeout);
            internal static ClientWaitSync glClientWaitSync;
            internal delegate void ColorMask(bool red, bool green, bool blue, bool alpha);
            internal static ColorMask glColorMask;
            internal delegate void CompileShader(UInt32 shader);
            internal static CompileShader glCompileShader;
            internal delegate void CompressedTexImage1D(OpenGL.TextureTarget target, Int32 level, OpenGL.PixelInternalFormat internalformat, Int32 width, Int32 border, Int32 imageSize, IntPtr data);
            internal static CompressedTexImage1D glCompressedTexImage1D;
            internal delegate void CompressedTexImage2D(OpenGL.TextureTarget target, Int32 level, OpenGL.PixelInternalFormat internalformat, Int32 width, Int32 height, Int32 border, Int32 imageSize, IntPtr data);
            internal static CompressedTexImage2D glCompressedTexImage2D;
            internal delegate void CompressedTexImage3D(OpenGL.TextureTarget target, Int32 level, OpenGL.PixelInternalFormat internalformat, Int32 width, Int32 height, Int32 depth, Int32 border, Int32 imageSize, IntPtr data);
            internal static CompressedTexImage3D glCompressedTexImage3D;
            internal delegate void CompressedTexSubImage1D(OpenGL.TextureTarget target, Int32 level, Int32 xoffset, Int32 width, OpenGL.PixelFormat format, Int32 imageSize, IntPtr data);
            internal static CompressedTexSubImage1D glCompressedTexSubImage1D;
            internal delegate void CompressedTexSubImage2D(OpenGL.TextureTarget target, Int32 level, Int32 xoffset, Int32 yoffset, Int32 width, Int32 height, OpenGL.PixelFormat format, Int32 imageSize, IntPtr data);
            internal static CompressedTexSubImage2D glCompressedTexSubImage2D;
            internal delegate void CompressedTexSubImage3D(OpenGL.TextureTarget target, Int32 level, Int32 xoffset, Int32 yoffset, Int32 zoffset, Int32 width, Int32 height, Int32 depth, OpenGL.PixelFormat format, Int32 imageSize, IntPtr data);
            internal static CompressedTexSubImage3D glCompressedTexSubImage3D;
            internal delegate void CopyBufferSubData(OpenGL.BufferTarget readTarget, OpenGL.BufferTarget writeTarget, IntPtr readOffset, IntPtr writeOffset, IntPtr size);
            internal static CopyBufferSubData glCopyBufferSubData;
            internal delegate void CopyTexImage1D(OpenGL.TextureTarget target, Int32 level, OpenGL.PixelInternalFormat internalformat, Int32 x, Int32 y, Int32 width, Int32 border);
            internal static CopyTexImage1D glCopyTexImage1D;
            internal delegate void CopyTexImage2D(OpenGL.TextureTarget target, Int32 level, OpenGL.PixelInternalFormat internalformat, Int32 x, Int32 y, Int32 width, Int32 height, Int32 border);
            internal static CopyTexImage2D glCopyTexImage2D;
            internal delegate void CopyTexSubImage1D(OpenGL.TextureTarget target, Int32 level, Int32 xoffset, Int32 x, Int32 y, Int32 width);
            internal static CopyTexSubImage1D glCopyTexSubImage1D;
            internal delegate void CopyTexSubImage2D(OpenGL.TextureTarget target, Int32 level, Int32 xoffset, Int32 yoffset, Int32 x, Int32 y, Int32 width, Int32 height);
            internal static CopyTexSubImage2D glCopyTexSubImage2D;
            internal delegate void CopyTexSubImage3D(OpenGL.TextureTarget target, Int32 level, Int32 xoffset, Int32 yoffset, Int32 zoffset, Int32 x, Int32 y, Int32 width, Int32 height);
            internal static CopyTexSubImage3D glCopyTexSubImage3D;
            internal delegate UInt32 CreateProgram();
            internal static CreateProgram glCreateProgram;
            internal delegate UInt32 CreateShader(OpenGL.ShaderType type);
            internal static CreateShader glCreateShader;
            internal delegate void CullFace(OpenGL.CullFaceMode mode);
            internal static CullFace glCullFace;
            internal delegate void DeleteBuffers(Int32 n, UInt32[] buffers);
            internal static DeleteBuffers glDeleteBuffers;
            internal delegate void DeleteFramebuffers(Int32 n, UInt32[] framebuffers);
            internal static DeleteFramebuffers glDeleteFramebuffers;
            internal delegate void DeleteProgram(UInt32 program);
            internal static DeleteProgram glDeleteProgram;
            internal delegate void DeleteQueries(Int32 n, UInt32[] ids);
            internal static DeleteQueries glDeleteQueries;
            internal delegate void DeleteRenderbuffers(Int32 n, UInt32[] renderbuffers);
            internal static DeleteRenderbuffers glDeleteRenderbuffers;
            internal delegate void DeleteShader(UInt32 shader);
            internal static DeleteShader glDeleteShader;
            internal delegate void DeleteSync(IntPtr sync);
            internal static DeleteSync glDeleteSync;
            internal delegate void DeleteTextures(Int32 n, UInt32[] textures);
            internal static DeleteTextures glDeleteTextures;
            internal delegate void DeleteTransformFeedbacksNV(Int32 n, UInt32[] ids);
            internal static DeleteTransformFeedbacksNV glDeleteTransformFeedbacksNV;
            internal delegate void DeleteVertexArrays(Int32 n, UInt32[] arrays);
            internal static DeleteVertexArrays glDeleteVertexArrays;
            internal delegate void DepthFunc(OpenGL.DepthFunction func);
            internal static DepthFunc glDepthFunc;
            internal delegate void DepthMask(bool flag);
            internal static DepthMask glDepthMask;
            internal delegate void DepthRange(Double near, Double far);
            internal static DepthRange glDepthRange;
            internal delegate void DetachShader(UInt32 program, UInt32 shader);
            internal static DetachShader glDetachShader;
            internal delegate void Disable(OpenGL.EnableCap cap);
            internal static Disable glDisable;
            internal delegate void DisableVertexAttribArray(UInt32 index);
            internal static DisableVertexAttribArray glDisableVertexAttribArray;
            internal delegate void DrawArrays(OpenGL.BeginMode mode, Int32 first, Int32 count);
            internal static DrawArrays glDrawArrays;
            internal delegate void DrawArraysInstanced(OpenGL.BeginMode mode, Int32 first, Int32 count, Int32 primcount);
            internal static DrawArraysInstanced glDrawArraysInstanced;
            internal delegate void DrawBuffer(OpenGL.DrawBufferMode mode);
            internal static DrawBuffer glDrawBuffer;
            internal delegate void DrawBuffers(Int32 n, OpenGL.DrawBuffersEnum[] bufs);
            internal static DrawBuffers glDrawBuffers;
            internal delegate void DrawElements(OpenGL.BeginMode mode, Int32 count, OpenGL.DrawElementsType type, IntPtr indices);
            internal static DrawElements glDrawElements;
            internal delegate void DrawElementsBaseVertex(OpenGL.BeginMode mode, Int32 count, OpenGL.DrawElementsType type, IntPtr indices, Int32 basevertex);
            internal static DrawElementsBaseVertex glDrawElementsBaseVertex;
            internal delegate void DrawElementsInstanced(OpenGL.BeginMode mode, Int32 count, OpenGL.DrawElementsType type, IntPtr indices, Int32 primcount);
            internal static DrawElementsInstanced glDrawElementsInstanced;
            internal delegate void DrawElementsInstancedBaseVertex(OpenGL.BeginMode mode, Int32 count, OpenGL.DrawElementsType type, IntPtr indices, Int32 primcount, Int32 basevertex);
            internal static DrawElementsInstancedBaseVertex glDrawElementsInstancedBaseVertex;
            internal delegate void DrawRangeElements(OpenGL.BeginMode mode, UInt32 start, UInt32 end, Int32 count, OpenGL.DrawElementsType type, IntPtr indices);
            internal static DrawRangeElements glDrawRangeElements;
            internal delegate void DrawRangeElementsBaseVertex(OpenGL.BeginMode mode, UInt32 start, UInt32 end, Int32 count, OpenGL.DrawElementsType type, IntPtr indices, Int32 basevertex);
            internal static DrawRangeElementsBaseVertex glDrawRangeElementsBaseVertex;
            internal delegate void DrawTransformFeedbackNV(OpenGL.NvTransformFeedback2 mode, UInt32 id);
            internal static DrawTransformFeedbackNV glDrawTransformFeedbackNV;
            internal delegate void Enable(OpenGL.EnableCap cap);
            internal static Enable glEnable;
            internal delegate void EnableVertexAttribArray(UInt32 index);
            internal static EnableVertexAttribArray glEnableVertexAttribArray;
            internal delegate void EndConditionalRenderNV();
            internal static EndConditionalRenderNV glEndConditionalRenderNV;
            internal delegate void EndQuery(OpenGL.QueryTarget target);
            internal static EndQuery glEndQuery;
            internal delegate void EndTransformFeedback();
            internal static EndTransformFeedback glEndTransformFeedback;
            internal delegate IntPtr FenceSync(OpenGL.ArbSync condition, UInt32 flags);
            internal static FenceSync glFenceSync;
            internal delegate void Finish();
            internal static Finish glFinish;
            internal delegate void Flush();
            internal static Flush glFlush;
            internal delegate void FlushMappedBufferRange(OpenGL.BufferTarget target, IntPtr offset, IntPtr length);
            internal static FlushMappedBufferRange glFlushMappedBufferRange;
            internal delegate void FramebufferRenderbuffer(OpenGL.FramebufferTarget target, OpenGL.FramebufferAttachment attachment, OpenGL.RenderbufferTarget renderbuffertarget, UInt32 renderbuffer);
            internal static FramebufferRenderbuffer glFramebufferRenderbuffer;
            internal delegate void FramebufferTexture(OpenGL.FramebufferTarget target, OpenGL.FramebufferAttachment attachment, UInt32 texture, Int32 level);
            internal static FramebufferTexture glFramebufferTexture;
            internal delegate void FramebufferTextureFace(OpenGL.Version32 target, OpenGL.Version32 attachment, UInt32 texture, Int32 level, OpenGL.Version32 face);
            internal static FramebufferTextureFace glFramebufferTextureFace;
            internal delegate void FramebufferTextureLayer(OpenGL.FramebufferTarget target, OpenGL.FramebufferAttachment attachment, UInt32 texture, Int32 level, Int32 layer);
            internal static FramebufferTextureLayer glFramebufferTextureLayer;
            internal delegate void FrontFace(OpenGL.FrontFaceDirection mode);
            internal static FrontFace glFrontFace;
            internal delegate void GenBuffers(Int32 n, [OutAttribute] UInt32[] buffers);
            internal static GenBuffers glGenBuffers;
            internal delegate void GenFramebuffers(Int32 n, [OutAttribute] UInt32[] framebuffers);
            internal static GenFramebuffers glGenFramebuffers;
            internal delegate void GenQueries(Int32 n, [OutAttribute] UInt32[] ids);
            internal static GenQueries glGenQueries;
            internal delegate void GenRenderbuffers(Int32 n, [OutAttribute] UInt32[] renderbuffers);
            internal static GenRenderbuffers glGenRenderbuffers;
            internal delegate void GenTextures(Int32 n, [OutAttribute] UInt32[] textures);
            internal static GenTextures glGenTextures;
            internal delegate void GenTransformFeedbacksNV(Int32 n, [OutAttribute] UInt32[] ids);
            internal static GenTransformFeedbacksNV glGenTransformFeedbacksNV;
            internal delegate void GenVertexArrays(Int32 n, [OutAttribute] UInt32[] arrays);
            internal static GenVertexArrays glGenVertexArrays;
            internal delegate void GenerateMipmap(OpenGL.GenerateMipmapTarget target);
            internal static GenerateMipmap glGenerateMipmap;
            internal delegate void GetBooleanv(OpenGL.GetPName pname, [OutAttribute] bool[] @params);
            internal static GetBooleanv glGetBooleanv;
            internal delegate void GetDoublev(OpenGL.GetPName pname, [OutAttribute] Double[] @params);
            internal static GetDoublev glGetDoublev;
            internal delegate void GetFloatv(OpenGL.GetPName pname, [OutAttribute] Single[] @params);
            internal static GetFloatv glGetFloatv;
            internal delegate void GetIntegerv(OpenGL.GetPName pname, [OutAttribute] Int32[] @params);
            internal static GetIntegerv glGetIntegerv;
            internal delegate void GetInteger64v(OpenGL.ArbSync pname, [OutAttribute] Int64[] @params);
            internal static GetInteger64v glGetInteger64v;
            internal delegate void GetActiveAttrib(UInt32 program, UInt32 index, Int32 bufSize, [OutAttribute] Int32[] length, [OutAttribute] Int32[] size, [OutAttribute] OpenGL.ActiveAttribType[] type, [OutAttribute] System.Text.StringBuilder name);
            internal static GetActiveAttrib glGetActiveAttrib;
            internal delegate void GetActiveUniform(UInt32 program, UInt32 index, Int32 bufSize, [OutAttribute] Int32[] length, [OutAttribute] Int32[] size, [OutAttribute] OpenGL.ActiveUniformType[] type, [OutAttribute] System.Text.StringBuilder name);
            internal static GetActiveUniform glGetActiveUniform;
            internal delegate void GetActiveUniformBlockiv(UInt32 program, UInt32 uniformBlockIndex, OpenGL.ActiveUniformBlockParameter pname, [OutAttribute] Int32[] @params);
            internal static GetActiveUniformBlockiv glGetActiveUniformBlockiv;
            internal delegate void GetActiveUniformBlockName(UInt32 program, UInt32 uniformBlockIndex, Int32 bufSize, [OutAttribute] Int32[] length, [OutAttribute] System.Text.StringBuilder uniformBlockName);
            internal static GetActiveUniformBlockName glGetActiveUniformBlockName;
            internal delegate void GetActiveUniformName(UInt32 program, UInt32 uniformIndex, Int32 bufSize, [OutAttribute] Int32[] length, [OutAttribute] System.Text.StringBuilder uniformName);
            internal static GetActiveUniformName glGetActiveUniformName;
            internal delegate void GetAttachedShaders(UInt32 program, Int32 maxCount, [OutAttribute] Int32[] count, [OutAttribute] UInt32[] obj);
            internal static GetAttachedShaders glGetAttachedShaders;
            internal delegate Int32 GetAttribLocation(UInt32 program, String name);
            internal static GetAttribLocation glGetAttribLocation;
            internal delegate void GetBufferParameteriv(OpenGL.BufferTarget target, OpenGL.BufferParameterName pname, [OutAttribute] Int32[] @params);
            internal static GetBufferParameteriv glGetBufferParameteriv;
            internal delegate void GetBufferPointerv(OpenGL.BufferTarget target, OpenGL.BufferPointer pname, [OutAttribute] IntPtr @params);
            internal static GetBufferPointerv glGetBufferPointerv;
            internal delegate void GetBufferSubData(OpenGL.BufferTarget target, IntPtr offset, IntPtr size, [OutAttribute] IntPtr data);
            internal static GetBufferSubData glGetBufferSubData;
            internal delegate void GetCompressedTexImage(OpenGL.TextureTarget target, Int32 level, [OutAttribute] IntPtr img);
            internal static GetCompressedTexImage glGetCompressedTexImage;
            internal delegate OpenGL.ErrorCode GetError();
            internal static GetError glGetError;
            internal delegate Int32 GetFragDataLocation(UInt32 program, String name);
            internal static GetFragDataLocation glGetFragDataLocation;
            internal delegate void GetFramebufferAttachmentParameteriv(OpenGL.FramebufferTarget target, OpenGL.FramebufferAttachment attachment, OpenGL.FramebufferParameterName pname, [OutAttribute] Int32[] @params);
            internal static GetFramebufferAttachmentParameteriv glGetFramebufferAttachmentParameteriv;
            internal delegate void GetMultisamplefv(OpenGL.GetMultisamplePName pname, UInt32 index, [OutAttribute] Single[] val);
            internal static GetMultisamplefv glGetMultisamplefv;
            internal delegate void GetProgramiv(UInt32 program, OpenGL.ProgramParameter pname, [OutAttribute] Int32[] @params);
            internal static GetProgramiv glGetProgramiv;
            internal delegate void GetProgramInfoLog(UInt32 program, Int32 bufSize, [OutAttribute] Int32[] length, [OutAttribute] System.Text.StringBuilder infoLog);
            internal static GetProgramInfoLog glGetProgramInfoLog;
            internal delegate void GetQueryObjectiv(UInt32 id, OpenGL.GetQueryObjectParam pname, [OutAttribute] Int32[] @params);
            internal static GetQueryObjectiv glGetQueryObjectiv;
            internal delegate void GetQueryObjectuiv(UInt32 id, OpenGL.GetQueryObjectParam pname, [OutAttribute] UInt32[] @params);
            internal static GetQueryObjectuiv glGetQueryObjectuiv;
            internal delegate void GetQueryiv(OpenGL.QueryTarget target, OpenGL.GetQueryParam pname, [OutAttribute] Int32[] @params);
            internal static GetQueryiv glGetQueryiv;
            internal delegate void GetRenderbufferParameteriv(OpenGL.RenderbufferTarget target, OpenGL.RenderbufferParameterName pname, [OutAttribute] Int32[] @params);
            internal static GetRenderbufferParameteriv glGetRenderbufferParameteriv;
            internal delegate void GetShaderiv(UInt32 shader, OpenGL.ShaderParameter pname, [OutAttribute] Int32[] @params);
            internal static GetShaderiv glGetShaderiv;
            internal delegate void GetShaderInfoLog(UInt32 shader, Int32 bufSize, [OutAttribute] Int32[] length, [OutAttribute] System.Text.StringBuilder infoLog);
            internal static GetShaderInfoLog glGetShaderInfoLog;
            internal delegate void GetShaderSource(UInt32 shader, Int32 bufSize, [OutAttribute] Int32[] length, [OutAttribute] System.Text.StringBuilder source);
            internal static GetShaderSource glGetShaderSource;
            internal delegate System.IntPtr GetString(OpenGL.StringName name);
            internal static GetString glGetString;
            internal delegate System.IntPtr GetStringi(OpenGL.StringName name, UInt32 index);
            internal static GetStringi glGetStringi;
            internal delegate void GetSynciv(IntPtr sync, OpenGL.ArbSync pname, Int32 bufSize, [OutAttribute] Int32[] length, [OutAttribute] Int32[] values);
            internal static GetSynciv glGetSynciv;
            internal delegate void GetTexImage(OpenGL.TextureTarget target, Int32 level, OpenGL.PixelFormat format, OpenGL.PixelType type, [OutAttribute] IntPtr pixels);
            internal static GetTexImage glGetTexImage;
            internal delegate void GetTexParameterfv(OpenGL.TextureTarget target, OpenGL.GetTextureParameter pname, [OutAttribute] Single[] @params);
            internal static GetTexParameterfv glGetTexParameterfv;
            internal delegate void GetTexParameteriv(OpenGL.TextureTarget target, OpenGL.GetTextureParameter pname, [OutAttribute] Int32[] @params);
            internal static GetTexParameteriv glGetTexParameteriv;
            internal delegate void GetTransformFeedbackVarying(UInt32 program, UInt32 index, Int32 bufSize, [OutAttribute] Int32[] length, [OutAttribute] Int32[] size, [OutAttribute] OpenGL.ActiveAttribType[] type, [OutAttribute] System.Text.StringBuilder name);
            internal static GetTransformFeedbackVarying glGetTransformFeedbackVarying;
            internal delegate void GetUniformfv(UInt32 program, Int32 location, [OutAttribute] Single[] @params);
            internal static GetUniformfv glGetUniformfv;
            internal delegate void GetUniformiv(UInt32 program, Int32 location, [OutAttribute] Int32[] @params);
            internal static GetUniformiv glGetUniformiv;
            internal delegate Int32 GetUniformLocation(UInt32 program, String name);
            internal static GetUniformLocation glGetUniformLocation;
            internal delegate void GetVertexAttribdv(UInt32 index, OpenGL.VertexAttribParameter pname, [OutAttribute] Double[] @params);
            internal static GetVertexAttribdv glGetVertexAttribdv;
            internal delegate void GetVertexAttribfv(UInt32 index, OpenGL.VertexAttribParameter pname, [OutAttribute] Single[] @params);
            internal static GetVertexAttribfv glGetVertexAttribfv;
            internal delegate void GetVertexAttribiv(UInt32 index, OpenGL.VertexAttribParameter pname, [OutAttribute] Int32[] @params);
            internal static GetVertexAttribiv glGetVertexAttribiv;
            internal delegate void GetVertexAttribIiv(UInt32 index, OpenGL.VertexAttribParameter pname, [OutAttribute] Int32[] @params);
            internal static GetVertexAttribIiv glGetVertexAttribIiv;
            internal delegate void GetVertexAttribIuiv(UInt32 index, OpenGL.VertexAttribParameter pname, [OutAttribute] UInt32[] @params);
            internal static GetVertexAttribIuiv glGetVertexAttribIuiv;
            internal delegate void GetVertexAttribLdv(UInt32 index, OpenGL.VertexAttribParameter pname, [OutAttribute] Double[] @params);
            internal static GetVertexAttribLdv glGetVertexAttribLdv;
            internal delegate void GetVertexAttribPointerv(UInt32 index, OpenGL.VertexAttribPointerParameter pname, [OutAttribute] IntPtr pointer);
            internal static GetVertexAttribPointerv glGetVertexAttribPointerv;
            internal delegate void Hint(OpenGL.HintTarget target, OpenGL.HintMode mode);
            internal static Hint glHint;
            internal delegate bool IsBuffer(UInt32 buffer);
            internal static IsBuffer glIsBuffer;
            internal delegate bool IsEnabled(OpenGL.EnableCap cap);
            internal static IsEnabled glIsEnabled;
            internal delegate bool IsFramebuffer(UInt32 framebuffer);
            internal static IsFramebuffer glIsFramebuffer;
            internal delegate bool IsProgram(UInt32 program);
            internal static IsProgram glIsProgram;
            internal delegate bool IsQuery(UInt32 id);
            internal static IsQuery glIsQuery;
            internal delegate bool IsRenderbuffer(UInt32 renderbuffer);
            internal static IsRenderbuffer glIsRenderbuffer;
            internal delegate bool IsShader(UInt32 shader);
            internal static IsShader glIsShader;
            internal delegate bool IsSync(IntPtr sync);
            internal static IsSync glIsSync;
            internal delegate bool IsTexture(UInt32 texture);
            internal static IsTexture glIsTexture;
            internal delegate bool IsTransformFeedbackNV(UInt32 id);
            internal static IsTransformFeedbackNV glIsTransformFeedbackNV;
            internal delegate bool IsVertexArray(UInt32 array);
            internal static IsVertexArray glIsVertexArray;
            internal delegate void LineWidth(Single width);
            internal static LineWidth glLineWidth;
            internal delegate void LinkProgram(UInt32 program);
            internal static LinkProgram glLinkProgram;
            internal delegate void LogicOp(OpenGL.LogicOp opcode);
            internal static LogicOp glLogicOp;
            internal delegate System.IntPtr MapBuffer(OpenGL.BufferTarget target, OpenGL.BufferAccess access);
            internal static MapBuffer glMapBuffer;
            internal delegate System.IntPtr MapBufferRange(OpenGL.BufferTarget target, IntPtr offset, IntPtr length, OpenGL.BufferAccessMask access);
            internal static MapBufferRange glMapBufferRange;
            internal delegate void MultiDrawArrays(OpenGL.BeginMode mode, [OutAttribute] Int32[] first, [OutAttribute] Int32[] count, Int32 primcount);
            internal static MultiDrawArrays glMultiDrawArrays;
            internal delegate void MultiDrawElements(OpenGL.BeginMode mode, Int32[] count, OpenGL.DrawElementsType type, IntPtr indices, Int32 primcount);
            internal static MultiDrawElements glMultiDrawElements;
            internal delegate void MultiDrawElementsBaseVertex(OpenGL.BeginMode mode, Int32[] count, OpenGL.DrawElementsType type, IntPtr indices, Int32 primcount, Int32[] basevertex);
            internal static MultiDrawElementsBaseVertex glMultiDrawElementsBaseVertex;
            internal delegate void PauseTransformFeedbackNV();
            internal static PauseTransformFeedbackNV glPauseTransformFeedbackNV;
            internal delegate void PixelStoref(OpenGL.PixelStoreParameter pname, Single param);
            internal static PixelStoref glPixelStoref;
            internal delegate void PixelStorei(OpenGL.PixelStoreParameter pname, Int32 param);
            internal static PixelStorei glPixelStorei;
            internal delegate void PointParameterf(OpenGL.PointParameterName pname, Single param);
            internal static PointParameterf glPointParameterf;
            internal delegate void PointParameteri(OpenGL.PointParameterName pname, Int32 param);
            internal static PointParameteri glPointParameteri;
            internal delegate void PointSize(float size);
            internal static PointSize glPointSize;
            internal delegate void PolygonMode(OpenGL.MaterialFace face, OpenGL.PolygonMode mode);
            internal static PolygonMode glPolygonMode;
            internal delegate void PolygonOffset(Single factor, Single units);
            internal static PolygonOffset glPolygonOffset;
            internal delegate void PrimitiveRestartIndex(UInt32 index);
            internal static PrimitiveRestartIndex glPrimitiveRestartIndex;
            internal delegate void ProgramParameteri(UInt32 program, OpenGL.Version32 pname, Int32 value);
            internal static ProgramParameteri glProgramParameteri;
            internal delegate void ProvokingVertex(OpenGL.ProvokingVertexMode mode);
            internal static ProvokingVertex glProvokingVertex;
            internal delegate void ProgramUniform1fEXT(UInt32 program, Int32 location, Single v0);
            internal static ProgramUniform1fEXT glProgramUniform1fEXT;
            internal delegate void ProgramUniform1fvEXT(UInt32 program, Int32 location, Int32 count, Single[] value);
            internal static ProgramUniform1fvEXT glProgramUniform1fvEXT;
            internal delegate void ProgramUniform1iEXT(UInt32 program, Int32 location, Int32 v0);
            internal static ProgramUniform1iEXT glProgramUniform1iEXT;
            internal delegate void ProgramUniform1ivEXT(UInt32 program, Int32 location, Int32 count, Int32[] value);
            internal static ProgramUniform1ivEXT glProgramUniform1ivEXT;
            internal delegate void ProgramUniform1uiEXT(UInt32 program, Int32 location, UInt32 v0);
            internal static ProgramUniform1uiEXT glProgramUniform1uiEXT;
            internal delegate void ProgramUniform1uivEXT(UInt32 program, Int32 location, Int32 count, UInt32[] value);
            internal static ProgramUniform1uivEXT glProgramUniform1uivEXT;
            internal delegate void ProgramUniform2fEXT(UInt32 program, Int32 location, Single v0, Single v1);
            internal static ProgramUniform2fEXT glProgramUniform2fEXT;
            internal delegate void ProgramUniform2fvEXT(UInt32 program, Int32 location, Int32 count, Single[] value);
            internal static ProgramUniform2fvEXT glProgramUniform2fvEXT;
            internal delegate void ProgramUniform2iEXT(UInt32 program, Int32 location, Int32 v0, Int32 v1);
            internal static ProgramUniform2iEXT glProgramUniform2iEXT;
            internal delegate void ProgramUniform2ivEXT(UInt32 program, Int32 location, Int32 count, Int32[] value);
            internal static ProgramUniform2ivEXT glProgramUniform2ivEXT;
            internal delegate void ProgramUniform2uiEXT(UInt32 program, Int32 location, UInt32 v0, UInt32 v1);
            internal static ProgramUniform2uiEXT glProgramUniform2uiEXT;
            internal delegate void ProgramUniform2uivEXT(UInt32 program, Int32 location, Int32 count, UInt32[] value);
            internal static ProgramUniform2uivEXT glProgramUniform2uivEXT;
            internal delegate void ProgramUniform3fEXT(UInt32 program, Int32 location, Single v0, Single v1, Single v2);
            internal static ProgramUniform3fEXT glProgramUniform3fEXT;
            internal delegate void ProgramUniform3fvEXT(UInt32 program, Int32 location, Int32 count, Single[] value);
            internal static ProgramUniform3fvEXT glProgramUniform3fvEXT;
            internal delegate void ProgramUniform3iEXT(UInt32 program, Int32 location, Int32 v0, Int32 v1, Int32 v2);
            internal static ProgramUniform3iEXT glProgramUniform3iEXT;
            internal delegate void ProgramUniform3ivEXT(UInt32 program, Int32 location, Int32 count, Int32[] value);
            internal static ProgramUniform3ivEXT glProgramUniform3ivEXT;
            internal delegate void ProgramUniform3uiEXT(UInt32 program, Int32 location, UInt32 v0, UInt32 v1, UInt32 v2);
            internal static ProgramUniform3uiEXT glProgramUniform3uiEXT;
            internal delegate void ProgramUniform3uivEXT(UInt32 program, Int32 location, Int32 count, UInt32[] value);
            internal static ProgramUniform3uivEXT glProgramUniform3uivEXT;
            internal delegate void ProgramUniform4fEXT(UInt32 program, Int32 location, Single v0, Single v1, Single v2, Single v3);
            internal static ProgramUniform4fEXT glProgramUniform4fEXT;
            internal delegate void ProgramUniform4fvEXT(UInt32 program, Int32 location, Int32 count, Single[] value);
            internal static ProgramUniform4fvEXT glProgramUniform4fvEXT;
            internal delegate void ProgramUniform4iEXT(UInt32 program, Int32 location, Int32 v0, Int32 v1, Int32 v2, Int32 v3);
            internal static ProgramUniform4iEXT glProgramUniform4iEXT;
            internal delegate void ProgramUniform4ivEXT(UInt32 program, Int32 location, Int32 count, Int32[] value);
            internal static ProgramUniform4ivEXT glProgramUniform4ivEXT;
            internal delegate void ProgramUniform4uiEXT(UInt32 program, Int32 location, UInt32 v0, UInt32 v1, UInt32 v2, UInt32 v3);
            internal static ProgramUniform4uiEXT glProgramUniform4uiEXT;
            internal delegate void ProgramUniform4uivEXT(UInt32 program, Int32 location, Int32 count, UInt32[] value);
            internal static ProgramUniform4uivEXT glProgramUniform4uivEXT;
            internal delegate void ProgramUniformMatrix2fvEXT(UInt32 program, Int32 location, Int32 count, bool transpose, Single[] value);
            internal static ProgramUniformMatrix2fvEXT glProgramUniformMatrix2fvEXT;
            internal delegate void ProgramUniformMatrix2x3fvEXT(UInt32 program, Int32 location, Int32 count, bool transpose, Single[] value);
            internal static ProgramUniformMatrix2x3fvEXT glProgramUniformMatrix2x3fvEXT;
            internal delegate void ProgramUniformMatrix2x4fvEXT(UInt32 program, Int32 location, Int32 count, bool transpose, Single[] value);
            internal static ProgramUniformMatrix2x4fvEXT glProgramUniformMatrix2x4fvEXT;
            internal delegate void ProgramUniformMatrix3fvEXT(UInt32 program, Int32 location, Int32 count, bool transpose, Single[] value);
            internal static ProgramUniformMatrix3fvEXT glProgramUniformMatrix3fvEXT;
            internal delegate void ProgramUniformMatrix3x2fvEXT(UInt32 program, Int32 location, Int32 count, bool transpose, Single[] value);
            internal static ProgramUniformMatrix3x2fvEXT glProgramUniformMatrix3x2fvEXT;
            internal delegate void ProgramUniformMatrix3x4fvEXT(UInt32 program, Int32 location, Int32 count, bool transpose, Single[] value);
            internal static ProgramUniformMatrix3x4fvEXT glProgramUniformMatrix3x4fvEXT;
            internal delegate void ProgramUniformMatrix4fvEXT(UInt32 program, Int32 location, Int32 count, bool transpose, Single[] value);
            internal static ProgramUniformMatrix4fvEXT glProgramUniformMatrix4fvEXT;
            internal delegate void ProgramUniformMatrix4x2fvEXT(UInt32 program, Int32 location, Int32 count, bool transpose, Single[] value);
            internal static ProgramUniformMatrix4x2fvEXT glProgramUniformMatrix4x2fvEXT;
            internal delegate void ProgramUniformMatrix4x3fvEXT(UInt32 program, Int32 location, Int32 count, bool transpose, Single[] value);
            internal static ProgramUniformMatrix4x3fvEXT glProgramUniformMatrix4x3fvEXT;
            internal delegate void ReadBuffer(OpenGL.ReadBufferMode mode);
            internal static ReadBuffer glReadBuffer;
            internal delegate void ReadPixels(Int32 x, Int32 y, Int32 width, Int32 height, OpenGL.PixelFormat format, OpenGL.PixelType type, [OutAttribute] Int32[] pixels);
            internal static ReadPixels glReadPixels;
            internal delegate void RenderbufferStorage(OpenGL.RenderbufferTarget target, OpenGL.RenderbufferStorage internalformat, Int32 width, Int32 height);
            internal static RenderbufferStorage glRenderbufferStorage;
            internal delegate void RenderbufferStorageMultisample(OpenGL.RenderbufferTarget target, Int32 samples, OpenGL.RenderbufferStorage internalformat, Int32 width, Int32 height);
            internal static RenderbufferStorageMultisample glRenderbufferStorageMultisample;
            internal delegate void ResumeTransformFeedbackNV();
            internal static ResumeTransformFeedbackNV glResumeTransformFeedbackNV;
            internal delegate void SampleCoverage(Single value, bool invert);
            internal static SampleCoverage glSampleCoverage;
            internal delegate void SampleMaski(UInt32 index, UInt32 mask);
            internal static SampleMaski glSampleMaski;
            internal delegate void Scissor(Int32 x, Int32 y, Int32 width, Int32 height);
            internal static Scissor glScissor;
            internal delegate void ShaderSource(UInt32 shader, Int32 count, String[] @string, Int32[] length);
            internal static ShaderSource glShaderSource;
            internal delegate void StencilFunc(OpenGL.StencilFunction func, Int32 @ref, UInt32 mask);
            internal static StencilFunc glStencilFunc;
            internal delegate void StencilFuncSeparate(OpenGL.StencilFace face, OpenGL.StencilFunction func, Int32 @ref, UInt32 mask);
            internal static StencilFuncSeparate glStencilFuncSeparate;
            internal delegate void StencilMask(UInt32 mask);
            internal static StencilMask glStencilMask;
            internal delegate void StencilMaskSeparate(OpenGL.StencilFace face, UInt32 mask);
            internal static StencilMaskSeparate glStencilMaskSeparate;
            internal delegate void StencilOp(OpenGL.StencilOp fail, OpenGL.StencilOp zfail, OpenGL.StencilOp zpass);
            internal static StencilOp glStencilOp;
            internal delegate void StencilOpSeparate(OpenGL.StencilFace face, OpenGL.StencilOp sfail, OpenGL.StencilOp dpfail, OpenGL.StencilOp dppass);
            internal static StencilOpSeparate glStencilOpSeparate;
            internal delegate void TexBuffer(OpenGL.TextureBufferTarget target, OpenGL.SizedInternalFormat internalformat, UInt32 buffer);
            internal static TexBuffer glTexBuffer;
            internal delegate void TexImage1D(OpenGL.TextureTarget target, Int32 level, OpenGL.PixelInternalFormat internalformat, Int32 width, Int32 border, OpenGL.PixelFormat format, OpenGL.PixelType type, IntPtr pixels);
            internal static TexImage1D glTexImage1D;
            internal delegate void TexImage2D(OpenGL.TextureTarget target, Int32 level, OpenGL.PixelInternalFormat internalformat, Int32 width, Int32 height, Int32 border, OpenGL.PixelFormat format, OpenGL.PixelType type, IntPtr pixels);
            internal static TexImage2D glTexImage2D;
            internal delegate void TexImage2DMultisample(OpenGL.TextureTargetMultisample target, Int32 samples, OpenGL.PixelInternalFormat internalformat, Int32 width, Int32 height, bool fixedsamplelocations);
            internal static TexImage2DMultisample glTexImage2DMultisample;
            internal delegate void TexImage3D(OpenGL.TextureTarget target, Int32 level, OpenGL.PixelInternalFormat internalformat, Int32 width, Int32 height, Int32 depth, Int32 border, OpenGL.PixelFormat format, OpenGL.PixelType type, IntPtr pixels);
            internal static TexImage3D glTexImage3D;
            internal delegate void TexImage3DMultisample(OpenGL.TextureTargetMultisample target, Int32 samples, OpenGL.PixelInternalFormat internalformat, Int32 width, Int32 height, Int32 depth, bool fixedsamplelocations);
            internal static TexImage3DMultisample glTexImage3DMultisample;
            internal delegate void TexParameterf(OpenGL.TextureTarget target, OpenGL.TextureParameterName pname, Single param);
            internal static TexParameterf glTexParameterf;
            internal delegate void TexParameteri(OpenGL.TextureTarget target, OpenGL.TextureParameterName pname, Int32 param);
            internal static TexParameteri glTexParameteri;
            internal delegate void TexSubImage1D(OpenGL.TextureTarget target, Int32 level, Int32 xoffset, Int32 width, OpenGL.PixelFormat format, OpenGL.PixelType type, IntPtr pixels);
            internal static TexSubImage1D glTexSubImage1D;
            internal delegate void TexSubImage2D(OpenGL.TextureTarget target, Int32 level, Int32 xoffset, Int32 yoffset, Int32 width, Int32 height, OpenGL.PixelFormat format, OpenGL.PixelType type, IntPtr pixels);
            internal static TexSubImage2D glTexSubImage2D;
            internal delegate void TexSubImage3D(OpenGL.TextureTarget target, Int32 level, Int32 xoffset, Int32 yoffset, Int32 zoffset, Int32 width, Int32 height, Int32 depth, OpenGL.PixelFormat format, OpenGL.PixelType type, IntPtr pixels);
            internal static TexSubImage3D glTexSubImage3D;
            internal delegate void TransformFeedbackVaryings(UInt32 program, Int32 count, String[] varyings, OpenGL.TransformFeedbackMode bufferMode);
            internal static TransformFeedbackVaryings glTransformFeedbackVaryings;
            internal delegate void Uniform1f(Int32 location, Single v0);
            internal static Uniform1f glUniform1f;
            internal delegate void Uniform1fv(Int32 location, Int32 count, Single[] value);
            internal static Uniform1fv glUniform1fv;
            internal delegate void Uniform1i(Int32 location, Int32 v0);
            internal static Uniform1i glUniform1i;
            internal delegate void Uniform1iv(Int32 location, Int32 count, Int32[] value);
            internal static Uniform1iv glUniform1iv;
            internal delegate void Uniform1ui(Int32 location, UInt32 v0);
            internal static Uniform1ui glUniform1ui;
            internal delegate void Uniform1uiv(Int32 location, Int32 count, UInt32[] value);
            internal static Uniform1uiv glUniform1uiv;
            internal delegate void Uniform2f(Int32 location, Single v0, Single v1);
            internal static Uniform2f glUniform2f;
            internal delegate void Uniform2fv(Int32 location, Int32 count, Single[] value);
            internal static Uniform2fv glUniform2fv;
            internal delegate void Uniform2i(Int32 location, Int32 v0, Int32 v1);
            internal static Uniform2i glUniform2i;
            internal delegate void Uniform2iv(Int32 location, Int32 count, Int32[] value);
            internal static Uniform2iv glUniform2iv;
            internal delegate void Uniform2ui(Int32 location, UInt32 v0, UInt32 v1);
            internal static Uniform2ui glUniform2ui;
            internal delegate void Uniform2uiv(Int32 location, Int32 count, UInt32[] value);
            internal static Uniform2uiv glUniform2uiv;
            internal delegate void Uniform3f(Int32 location, Single v0, Single v1, Single v2);
            internal static Uniform3f glUniform3f;
            internal delegate void Uniform3fv(Int32 location, Int32 count, Single[] value);
            internal static Uniform3fv glUniform3fv;
            internal delegate void Uniform3i(Int32 location, Int32 v0, Int32 v1, Int32 v2);
            internal static Uniform3i glUniform3i;
            internal delegate void Uniform3iv(Int32 location, Int32 count, Int32[] value);
            internal static Uniform3iv glUniform3iv;
            internal delegate void Uniform3ui(Int32 location, UInt32 v0, UInt32 v1, UInt32 v2);
            internal static Uniform3ui glUniform3ui;
            internal delegate void Uniform3uiv(Int32 location, Int32 count, UInt32[] value);
            internal static Uniform3uiv glUniform3uiv;
            internal delegate void Uniform4f(Int32 location, Single v0, Single v1, Single v2, Single v3);
            internal static Uniform4f glUniform4f;
            internal delegate void Uniform4fv(Int32 location, Int32 count, Single[] value);
            internal static Uniform4fv glUniform4fv;
            internal delegate void Uniform4i(Int32 location, Int32 v0, Int32 v1, Int32 v2, Int32 v3);
            internal static Uniform4i glUniform4i;
            internal delegate void Uniform4iv(Int32 location, Int32 count, Int32[] value);
            internal static Uniform4iv glUniform4iv;
            internal delegate void Uniform4ui(Int32 location, UInt32 v0, UInt32 v1, UInt32 v2, UInt32 v3);
            internal static Uniform4ui glUniform4ui;
            internal delegate void Uniform4uiv(Int32 location, Int32 count, UInt32[] value);
            internal static Uniform4uiv glUniform4uiv;
            internal delegate void UniformMatrix2fv(Int32 location, Int32 count, bool transpose, Single[] value);
            internal static UniformMatrix2fv glUniformMatrix2fv;
            internal delegate void UniformMatrix2x3fv(Int32 location, Int32 count, bool transpose, Single[] value);
            internal static UniformMatrix2x3fv glUniformMatrix2x3fv;
            internal delegate void UniformMatrix2x4fv(Int32 location, Int32 count, bool transpose, Single[] value);
            internal static UniformMatrix2x4fv glUniformMatrix2x4fv;
            internal delegate void UniformMatrix3fv(Int32 location, Int32 count, bool transpose, Single[] value);
            internal static UniformMatrix3fv glUniformMatrix3fv;
            internal delegate void UniformMatrix3x2fv(Int32 location, Int32 count, bool transpose, Single[] value);
            internal static UniformMatrix3x2fv glUniformMatrix3x2fv;
            internal delegate void UniformMatrix3x4fv(Int32 location, Int32 count, bool transpose, Single[] value);
            internal static UniformMatrix3x4fv glUniformMatrix3x4fv;
            internal delegate void UniformMatrix4fv(Int32 location, Int32 count, bool transpose, Single[] value);
            internal static UniformMatrix4fv glUniformMatrix4fv;
            internal delegate void UniformMatrix4x2fv(Int32 location, Int32 count, bool transpose, Single[] value);
            internal static UniformMatrix4x2fv glUniformMatrix4x2fv;
            internal delegate void UniformMatrix4x3fv(Int32 location, Int32 count, bool transpose, Single[] value);
            internal static UniformMatrix4x3fv glUniformMatrix4x3fv;
            internal delegate void UniformBlockBinding(UInt32 program, UInt32 uniformBlockIndex, UInt32 uniformBlockBinding);
            internal static UniformBlockBinding glUniformBlockBinding;
            internal delegate bool UnmapBuffer(OpenGL.BufferTarget target);
            internal static UnmapBuffer glUnmapBuffer;
            internal delegate void UseProgram(UInt32 program);
            internal static UseProgram glUseProgram;
            internal delegate void VertexAttrib1d(UInt32 index, Double x);
            internal static VertexAttrib1d glVertexAttrib1d;
            internal delegate void VertexAttrib1dv(UInt32 index, Double[] v);
            internal static VertexAttrib1dv glVertexAttrib1dv;
            internal delegate void VertexAttrib1f(UInt32 index, Single x);
            internal static VertexAttrib1f glVertexAttrib1f;
            internal delegate void VertexAttrib1fv(UInt32 index, Single[] v);
            internal static VertexAttrib1fv glVertexAttrib1fv;
            internal delegate void VertexAttrib1s(UInt32 index, Int16 x);
            internal static VertexAttrib1s glVertexAttrib1s;
            internal delegate void VertexAttrib1sv(UInt32 index, Int16[] v);
            internal static VertexAttrib1sv glVertexAttrib1sv;
            internal delegate void VertexAttrib2d(UInt32 index, Double x, Double y);
            internal static VertexAttrib2d glVertexAttrib2d;
            internal delegate void VertexAttrib2dv(UInt32 index, Double[] v);
            internal static VertexAttrib2dv glVertexAttrib2dv;
            internal delegate void VertexAttrib2f(UInt32 index, Single x, Single y);
            internal static VertexAttrib2f glVertexAttrib2f;
            internal delegate void VertexAttrib2fv(UInt32 index, Single[] v);
            internal static VertexAttrib2fv glVertexAttrib2fv;
            internal delegate void VertexAttrib2s(UInt32 index, Int16 x, Int16 y);
            internal static VertexAttrib2s glVertexAttrib2s;
            internal delegate void VertexAttrib2sv(UInt32 index, Int16[] v);
            internal static VertexAttrib2sv glVertexAttrib2sv;
            internal delegate void VertexAttrib3d(UInt32 index, Double x, Double y, Double z);
            internal static VertexAttrib3d glVertexAttrib3d;
            internal delegate void VertexAttrib3dv(UInt32 index, Double[] v);
            internal static VertexAttrib3dv glVertexAttrib3dv;
            internal delegate void VertexAttrib3f(UInt32 index, Single x, Single y, Single z);
            internal static VertexAttrib3f glVertexAttrib3f;
            internal delegate void VertexAttrib3fv(UInt32 index, Single[] v);
            internal static VertexAttrib3fv glVertexAttrib3fv;
            internal delegate void VertexAttrib3s(UInt32 index, Int16 x, Int16 y, Int16 z);
            internal static VertexAttrib3s glVertexAttrib3s;
            internal delegate void VertexAttrib3sv(UInt32 index, Int16[] v);
            internal static VertexAttrib3sv glVertexAttrib3sv;
            internal delegate void VertexAttrib4bv(UInt32 index, SByte[] v);
            internal static VertexAttrib4bv glVertexAttrib4bv;
            internal delegate void VertexAttrib4d(UInt32 index, Double x, Double y, Double z, Double w);
            internal static VertexAttrib4d glVertexAttrib4d;
            internal delegate void VertexAttrib4dv(UInt32 index, Double[] v);
            internal static VertexAttrib4dv glVertexAttrib4dv;
            internal delegate void VertexAttrib4f(UInt32 index, Single x, Single y, Single z, Single w);
            internal static VertexAttrib4f glVertexAttrib4f;
            internal delegate void VertexAttrib4fv(UInt32 index, Single[] v);
            internal static VertexAttrib4fv glVertexAttrib4fv;
            internal delegate void VertexAttrib4iv(UInt32 index, Int32[] v);
            internal static VertexAttrib4iv glVertexAttrib4iv;
            internal delegate void VertexAttrib4Nbv(UInt32 index, SByte[] v);
            internal static VertexAttrib4Nbv glVertexAttrib4Nbv;
            internal delegate void VertexAttrib4Niv(UInt32 index, Int32[] v);
            internal static VertexAttrib4Niv glVertexAttrib4Niv;
            internal delegate void VertexAttrib4Nsv(UInt32 index, Int16[] v);
            internal static VertexAttrib4Nsv glVertexAttrib4Nsv;
            internal delegate void VertexAttrib4Nub(UInt32 index, Byte x, Byte y, Byte z, Byte w);
            internal static VertexAttrib4Nub glVertexAttrib4Nub;
            internal delegate void VertexAttrib4Nubv(UInt32 index, Byte[] v);
            internal static VertexAttrib4Nubv glVertexAttrib4Nubv;
            internal delegate void VertexAttrib4Nuiv(UInt32 index, UInt32[] v);
            internal static VertexAttrib4Nuiv glVertexAttrib4Nuiv;
            internal delegate void VertexAttrib4Nusv(UInt32 index, UInt16[] v);
            internal static VertexAttrib4Nusv glVertexAttrib4Nusv;
            internal delegate void VertexAttrib4s(UInt32 index, Int16 x, Int16 y, Int16 z, Int16 w);
            internal static VertexAttrib4s glVertexAttrib4s;
            internal delegate void VertexAttrib4sv(UInt32 index, Int16[] v);
            internal static VertexAttrib4sv glVertexAttrib4sv;
            internal delegate void VertexAttrib4ubv(UInt32 index, Byte[] v);
            internal static VertexAttrib4ubv glVertexAttrib4ubv;
            internal delegate void VertexAttrib4uiv(UInt32 index, UInt32[] v);
            internal static VertexAttrib4uiv glVertexAttrib4uiv;
            internal delegate void VertexAttrib4usv(UInt32 index, UInt16[] v);
            internal static VertexAttrib4usv glVertexAttrib4usv;
            internal delegate void VertexAttribI1i(UInt32 index, Int32 x);
            internal static VertexAttribI1i glVertexAttribI1i;
            internal delegate void VertexAttribI1iv(UInt32 index, Int32[] v);
            internal static VertexAttribI1iv glVertexAttribI1iv;
            internal delegate void VertexAttribI1ui(UInt32 index, UInt32 x);
            internal static VertexAttribI1ui glVertexAttribI1ui;
            internal delegate void VertexAttribI1uiv(UInt32 index, UInt32[] v);
            internal static VertexAttribI1uiv glVertexAttribI1uiv;
            internal delegate void VertexAttribI2i(UInt32 index, Int32 x, Int32 y);
            internal static VertexAttribI2i glVertexAttribI2i;
            internal delegate void VertexAttribI2iv(UInt32 index, Int32[] v);
            internal static VertexAttribI2iv glVertexAttribI2iv;
            internal delegate void VertexAttribI2ui(UInt32 index, UInt32 x, UInt32 y);
            internal static VertexAttribI2ui glVertexAttribI2ui;
            internal delegate void VertexAttribI2uiv(UInt32 index, UInt32[] v);
            internal static VertexAttribI2uiv glVertexAttribI2uiv;
            internal delegate void VertexAttribI3i(UInt32 index, Int32 x, Int32 y, Int32 z);
            internal static VertexAttribI3i glVertexAttribI3i;
            internal delegate void VertexAttribI3iv(UInt32 index, Int32[] v);
            internal static VertexAttribI3iv glVertexAttribI3iv;
            internal delegate void VertexAttribI3ui(UInt32 index, UInt32 x, UInt32 y, UInt32 z);
            internal static VertexAttribI3ui glVertexAttribI3ui;
            internal delegate void VertexAttribI3uiv(UInt32 index, UInt32[] v);
            internal static VertexAttribI3uiv glVertexAttribI3uiv;
            internal delegate void VertexAttribI4bv(UInt32 index, SByte[] v);
            internal static VertexAttribI4bv glVertexAttribI4bv;
            internal delegate void VertexAttribI4i(UInt32 index, Int32 x, Int32 y, Int32 z, Int32 w);
            internal static VertexAttribI4i glVertexAttribI4i;
            internal delegate void VertexAttribI4iv(UInt32 index, Int32[] v);
            internal static VertexAttribI4iv glVertexAttribI4iv;
            internal delegate void VertexAttribI4sv(UInt32 index, Int16[] v);
            internal static VertexAttribI4sv glVertexAttribI4sv;
            internal delegate void VertexAttribI4ubv(UInt32 index, Byte[] v);
            internal static VertexAttribI4ubv glVertexAttribI4ubv;
            internal delegate void VertexAttribI4ui(UInt32 index, UInt32 x, UInt32 y, UInt32 z, UInt32 w);
            internal static VertexAttribI4ui glVertexAttribI4ui;
            internal delegate void VertexAttribI4uiv(UInt32 index, UInt32[] v);
            internal static VertexAttribI4uiv glVertexAttribI4uiv;
            internal delegate void VertexAttribI4usv(UInt32 index, UInt16[] v);
            internal static VertexAttribI4usv glVertexAttribI4usv;
            internal delegate void VertexAttribDivisor(UInt32 index, UInt32 divisor);
            internal static VertexAttribDivisor glVertexAttribDivisor;
            internal delegate void VertexAttribPointer(UInt32 index, Int32 size, OpenGL.VertexAttribPointerType type, bool normalized, Int32 stride, IntPtr pointer);
            internal static VertexAttribPointer glVertexAttribPointer;
            internal delegate void Viewport(Int32 x, Int32 y, Int32 width, Int32 height);
            internal static Viewport glViewport;
            internal delegate void WaitSync(IntPtr sync, UInt32 flags, UInt64 timeout);
            internal static WaitSync glWaitSync;
            internal delegate void ActiveShaderProgram(UInt32 pipeline, UInt32 program);
            internal static ActiveShaderProgram glActiveShaderProgram;
            internal delegate void BeginQueryIndexed(UInt32 target, UInt32 index, UInt32 id);
            internal static BeginQueryIndexed glBeginQueryIndexed;
            internal delegate void BindFragDataLocationIndexed(UInt32 program, UInt32 colorNumber, UInt32 index, char[] name);
            internal static BindFragDataLocationIndexed glBindFragDataLocationIndexed;
            internal delegate void BindSampler(UInt32 unit, UInt32 sampler);
            internal static BindSampler glBindSampler;
            internal delegate Int32 CreateShaderProgram(OpenGL.ShaderType type, UInt32 count, string[] strings);
            internal static CreateShaderProgram glCreateShaderProgram;
            internal delegate void DeleteProgramPipelines(Int32 n, UInt32[] ids);
            internal static DeleteProgramPipelines glDeleteProgramPipelines;
            internal delegate void DepthRangeArrayv(UInt32 index, Double near, Double far);
            internal static DepthRangeArrayv glDepthRangeArrayv;
            internal delegate void DrawArraysIndirect(OpenGL.BeginMode mode, IntPtr indirect);
            internal static DrawArraysIndirect glDrawArraysIndirect;
            internal delegate void DrawTransformFeedbackStream(OpenGL.NvTransformFeedback2 mode, UInt32 id, UInt32 stream);
            internal static DrawTransformFeedbackStream glDrawTransformFeedbackStream;
            internal delegate void EndQueryIndexed(OpenGL.QueryTarget target, UInt32 index, UInt32 id);
            internal static EndQueryIndexed glEndQueryIndexed;
            internal delegate void GenProgramPipelines(Int32 n, [OutAttribute] UInt32[] pipelines);
            internal static GenProgramPipelines glGenProgramPipelines;
            internal delegate void GenSamplers(Int32 n, [OutAttribute] UInt32[] samplers);
            internal static GenSamplers glGenSamplers;
            internal delegate void GetFragDataIndex(UInt32 program, String name);
            internal static GetFragDataIndex glGetFragDataIndex;
            internal delegate void GetProgramBinary(UInt32 program, Int32 size, Int32[] length, Int32[] binaryFormat, IntPtr binary);
            internal static GetProgramBinary glGetProgramBinary;
            internal delegate void GetProgramPipelineiv(UInt32 pipeline, Int32 pname, [OutAttribute] Int32[] @params);
            internal static GetProgramPipelineiv glGetProgramPipelineiv;
            internal delegate void GetProgramPipelineInfoLog(UInt32 pipeline, Int32 bufSize, [OutAttribute] Int32[] length, [OutAttribute] System.Text.StringBuilder infoLog);
            internal static GetProgramPipelineInfoLog glGetProgramPipelineInfoLog;
            internal delegate void GetProgramStage(UInt32 program, OpenGL.ShaderType shadertype, Int32 pname, [OutAttribute] Int32[] @values);
            internal static GetProgramStage glGetProgramStage;
            internal delegate void GetQueryObjecti64v(UInt32 id, OpenGL.GetQueryObjectParam pname, [OutAttribute] UInt64[] @params);
            internal static GetQueryObjecti64v glGetQueryObjecti64v;
            internal delegate void GetQueryObjectui64v(UInt32 id, OpenGL.GetQueryObjectParam pname, [OutAttribute] UInt64[] @params);
            internal static GetQueryObjectui64v glGetQueryObjectui64v;
            internal delegate void GetSamplerParameterfv(UInt32 sampler, Int32 pname, [OutAttribute] Single[] @params);
            internal static GetSamplerParameterfv glGetSamplerParameterfv;
            internal delegate void GetSamplerParameteriv(UInt32 sampler, Int32 pname, [OutAttribute] Int32[] @params);
            internal static GetSamplerParameteriv glGetSamplerParameteriv;
            internal delegate void GetShaderPrecisionFormat(OpenGL.ShaderType shaderType, Int32 precisionType, Int32[] range, [OutAttribute] Int32[] precision);
            internal static GetShaderPrecisionFormat glGetShaderPrecisionFormat;
            internal delegate UInt32 GetUniformBlockIndex(UInt32 program, String uniformBlockName);
            internal static GetUniformBlockIndex glGetUniformBlockIndex;
            internal delegate UInt32 GetUniformIndices(UInt32 program, Int32 uniformCount, String[] uniformNames, UInt32[] uniformIndices);
            internal static GetUniformIndices glGetUniformIndices;
            internal delegate void GetUniformSubroutineuiv(OpenGL.ShaderType shaderType, Int32 location, [OutAttribute] UInt32[] values);
            internal static GetUniformSubroutineuiv glGetUniformSubroutineuiv;
            internal delegate bool IsProgramPipeline(UInt32 pipeline);
            internal static IsProgramPipeline glIsProgramPipeline;
            internal delegate bool IsSampler(UInt32 id);
            internal static IsSampler glIsSampler;
            internal delegate void PatchParameteri(Int32 pname, Int32 value);
            internal static PatchParameteri glPatchParameteri;
            internal delegate void PatchParameterfv(Int32 pname, Single value);
            internal static PatchParameterfv glPatchParameterfv;
            internal delegate void ProgramBinary(UInt32 program, Int32 binaryFormat, IntPtr binary, Int32 length);
            internal static ProgramBinary glProgramBinary;
            internal delegate void QueryCounter(UInt32 id, Int32 target);
            internal static QueryCounter glQueryCounter;
            internal delegate void ReleaseShaderCompiler();
            internal static ReleaseShaderCompiler glReleaseShaderCompiler;
            internal delegate void SamplerParameterf(UInt32 sampler, Int32 pname, Single param);
            internal static SamplerParameterf glSamplerParameterf;
            internal delegate void SamplerParameteri(UInt32 sampler, Int32 pname, Int32 param);
            internal static SamplerParameteri glSamplerParameteri;
            internal delegate void ScissorArrayv(UInt32 first, Int32 count, Int32[] v);
            internal static ScissorArrayv glScissorArrayv;
            internal delegate void ShaderBinary(Int32 count, UInt32[] shaders, Int32 binaryFormat, IntPtr binary, Int32 length);
            internal static ShaderBinary glShaderBinary;
            internal delegate void UniformSubroutinesuiv(ShaderType shaderType, Int32 count, UInt32[] indices);
            internal static UniformSubroutinesuiv glUniformSubroutinesuiv;
            internal delegate void UseProgramStages(UInt32 pipeline, Int32 bitField, UInt32 program);
            internal static UseProgramStages glUseProgramStages;
            internal delegate void ValidateProgram(UInt32 program);
            internal static ValidateProgram glValidateProgram;
            internal delegate void ValidateProgramPipeline(UInt32 pipeline);
            internal static ValidateProgramPipeline glValidateProgramPipeline;
            internal delegate void ViewportArray(UInt32 first, Int32 count, Single[] v);
            internal static ViewportArray glViewportArray;
            internal delegate void ViewportIndexedf(UInt32 index, Single x, Single y, Single w, Single h);
            internal static ViewportIndexedf glViewportIndexedf;
            internal delegate void ViewportIndexedfv(UInt32 index, Single[] v);
            internal static ViewportIndexedfv glViewportIndexedfv;
        }
    }
}
